### ISSUE TITLE
How to pass params to index() method

### ISSUE THREAD

**Issue by neubreed** [sagarrabadiya/PHP-Routing-clean-url#1]
Hi,

I want to use a url like /events/event-name and use events.php as the controller and the event-name as the parameter for the index method .. is that possible?

**Comment by sagarrabadiya** [comment]
currently after controller name 2nd part in uri is action so above should work if yiur url is like /events/index/event-name, if you need to pass params to index method its not possible right now i will update logic to accept parameters to index method in couole of days, Thanks for using this tiny library.. 👍

**Comment by neubreed** [comment]
Great! .. thanks for responding so quickly

**Comment by sagarrabadiya** [comment]
i have added support for the above now you can use this url and it will fallback to index method with params if the 2nd uri part is not method in controller

**Comment by neubreed** [comment]
Thanks! .. that's mostly working except if the parameter is committed .. say for the /events only URL

`Too few arguments to function events::index(), 0 passed`

**Comment by sagarrabadiya** [comment]
add default value to argument, like index($var = null) and that will work i think.

**Comment by neubreed** [comment]
Ok that makes sense .. That worked
